name: khudafinder
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pytest

  - pytorch
  - torchvision
  - torchaudio

  - tensorboard
  - moviepy

  - stable-baselines3

  - gymnasium
  - pygame
  - pymunk
